chompy/Models/BloggingViewModels/EditorViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Chompy.Models.BloggingViewModels
{
    public class EditorViewModel
    {
        public List<SelectListItem> BlogOptions { get; set; }

        [Required]
        [Display(Name = "Blog")]
        public int SelectedBlogId { get; set; }

        public int? PostId { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Url Path")]
        public string UrlPath { get; set; }

        [Required]
        [Display(Name = "Tags")]
        public string TagString { get; set; }

        [Required]
        public string Blurb { get; set; }

        public string Content { get; set; }

        public bool Publish { get; set; }

        public List<Post> Posts { get; set; }
    }
}

chompy/Models/BloggingViewModels/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Chompy.Models.BloggingViewModels
{
    public class PostViewModel
    {
        [Required]
        public Post Post { get; set; }

        public List<Post> MorePosts { get; set; }
    }
}

chompy/Models/BloggingViewModels/PostsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Chompy.Models.BloggingViewModels
{
    public class PostsViewModel
    {
        [Required]
        public string PostsJson { get; set; }
       
        [Required]
        public string TagsJson { get; set; }
    }
}

chompy/Controllers/BloggingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Chompy.Models;
using Chompy.Models.BloggingViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;

namespace Chompy.Controllers
{
    public class BloggingController : Controller
    {
        private BloggingContext _context;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public BloggingController(
            BloggingContext context,
            SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Posts()
        {
            ViewData["Message"] = "Your posts page.";

            List<Post> posts = _context
                    .Posts
                    .Include(p => p.PostTags)
                        .ThenInclude(pt => pt.Tag)
                    .Where(p => p.Published)
                    .ToList();

            List<Tag> tags = _context
                    .Tags
                    .ToList();

            PostsViewModel postsViewModel = new PostsViewModel() {
                PostsJson = JsonConvert.SerializeObject(posts, Formatting.Indented, new JsonSerializerSettings(){ ReferenceLoopHandling = ReferenceLoopHandling.Ignore }),
                TagsJson = JsonConvert.SerializeObject(tags),
            };

            return View(postsViewModel);
        }

        public IActionResult Post(string id)
        {
            PostViewModel postViewModel = null;

            try
            {
                postViewModel = new PostViewModel()
                {
                    Post = _context.Posts
                    .Where(p => p.Published)
                    .Single(p => p.UrlPath == id)
                };
            }
            catch (Exception ex)
            {
                // todo: Log
            }

            if(postViewModel == null)
            {
                return RedirectToAction("Posts");
            }

            postViewModel.MorePosts = _context
                .Posts
                .Where(p => p.PostId != postViewModel.Post.PostId && p.Published)
                .OrderByDescending(p => p.ModifiedTimestamp)
                .ToList();

            return View(postViewModel);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Editor(string id = null)
        {
            EditorViewModel editorViewModel;

            // If we have the url path to a post to edit
            if(id != null)
            {
                Post post = _context.Posts
                    .Include(p => p.PostTags)
                        .ThenInclude(pt => pt.Tag)
                    .Single(p => p.UrlPath == id);

                editorViewModel = new EditorViewModel()
                {
                    PostId = post.PostId,
                    Title = post.Title,
                    UrlPath = post.UrlPath,
                    TagString = string.Join(" ", post.PostTags.Select(pt => pt.Tag.Label)),
                    Blurb = post.Blurb,
                    Content = post.Content,
                };
            }
            else // If we have are create a new post
            {
                editorViewModel = new EditorViewModel()
                {
                    Title = "Enter your title",
                    UrlPath = "edit-the-url-here",
                    TagString = "enter-tags-here seperate-with-spaces",
                    Blurb = "Enter your blurb here",
                    Content = "<h2>Use this area to edit your post.</h2>",
                };
            }

            string userEmail = _userManager.GetUserAsync(this.User).Result.Email;

            editorViewModel.BlogOptions = _context.Blogs
                .Include(b => b.Publishers)
                    .ThenInclude(p => p.Person)
                .Where(b => b.Publishers.Select(p => p.Person.EmailAddress).Contains(userEmail))
                .Select(b => new SelectListItem() { Text = b.Name, Value = b.BlogId.ToString() })
                .ToList();

            // Order the posts for the sidebar with drafts first, then by descending mod timestamps.
            editorViewModel.Posts = _context
                .Posts
                .OrderBy(p => p.Published)
                    .ThenByDescending(p => p.ModifiedTimestamp)
                .ToList();
            
            return View(editorViewModel);
        }

        /// <summary>
        /// todo: [Bind(Include: "")]?
        /// </summary>
        /// <param name="editorViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [Route("[controller]/Editor/SaveDraftPost")]
        public IActionResult SaveDraftPost(EditorViewModel editorViewModel)
        {
            if (ModelState.IsValid)
            {
                editorViewModel.Publish = false;
                SaveEditorPost(editorViewModel);
            }

            return RedirectToAction("Editor", new { id = editorViewModel.UrlPath });
        }

        /// <summary>
        /// todo
        /// </summary>
        /// <param name="editorViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [Route("[controller]/Editor/PublishPost")]
        public IActionResult PublishPost(EditorViewModel editorViewModel)
        {
            if (ModelState.IsValid)
            {
                editorViewModel.Publish = true;
                SaveEditorPost(editorViewModel);
            }

            return RedirectToAction("Editor", new { id = editorViewModel.UrlPath });
        }

        /// <summary>
        /// todo
        /// </summary>
        /// <param name="editorViewModel"></param>
        private void SaveEditorPost(EditorViewModel editorViewModel)
        {
            // create/update the Post
            Post post;

            if (editorViewModel.PostId.HasValue)
            {
                post = _context.Posts.Single(p => p.PostId == editorViewModel.PostId);

                post.Title = editorViewModel.Title;
                post.UrlPath = editorViewModel.UrlPath;
                post.Blurb = editorViewModel.Blurb;
                post.Content = editorViewModel.Content;
                post.Published = editorViewModel.Publish;

                _context.Posts.Update(post);
            }
            else
            {
                post = new Post()
                {
                    BlogId = editorViewModel.SelectedBlogId,
                    Title = editorViewModel.Title,
                    UrlPath = editorViewModel.UrlPath,
                    Blurb = editorViewModel.Blurb,
                    Content = editorViewModel.Content,
                    Published = editorViewModel.Publish,
                };

                _context.Posts.Add(post);
            }

            _context.SaveChanges();

            List<string> tagStrings = editorViewModel.TagString.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries).ToList();

            // Insert new Tags
            Tag.InsertIfNotExists(_context, tagStrings);
            _context.SaveChanges();

            // Get the new Tags
            List<Tag> tags = _context
                .Tags
                .Where(t => tagStrings.Contains(t.Label))
                .ToList();

            List<PostTag> postTagsToInsert = tags.Select(t => new PostTag()
                {
                    PostId = post.PostId,
                    TagId = t.TagId,
                })
                .Where(pt1 => !_context.PostTags.Any(pt2 => pt1.PostId == pt2.PostId && pt1.TagId == pt2.TagId))
                .ToList();

            // Add new PostTags
            _context.PostTags
                .AddRange(postTagsToInsert);

            // Remove old PostTags
            _context.PostTags.RemoveRange(
                _context.PostTags.Where(pt => pt.PostId == post.PostId && !tags.Contains(pt.Tag)));

            _context.SaveChanges();
        }
    }
}

chompy/Views/Blogging/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

chompy/Views/Blogging/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

chompy/Views/Blogging/Editor.cshtml
@model Chompy.Models.BloggingViewModels.EditorViewModel

<!-- todo: replace prod scripts with CDNs-->
@section Scripts {
    <environment names="Development">
        <script type="text/javascript" src="~/lib/medium-editor/dist/js/medium-editor.js"></script>
        <script type="text/javascript" src="~/lib/medium-editor-custom-html/src/custom-html.js"></script>
        <script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
        <script type="text/javascript" src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script type="text/javascript" src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script type="text/javascript" src="~/lib/medium-editor/dist/js/medium-editor.min.js"></script>
        <script type="text/javascript" src="~/lib/medium-editor-custom-html/src/custom-html.min.js"></script>
        <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
        <script type="text/javascript" src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script type="text/javascript" src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    </environment>

    @*Initialize the MediumEditor*@
    <script>
        var editor = new MediumEditor('.editable');
    </script>
    <script>
        $('#Title').on('input', function () {
            var text = $('#Title').val();
            text = text.toLowerCase().replace(/[^0-9a-zA-Z ]/gi, '').replace(/ /gi, '-');
            $('#UrlPath').val(text);
        });
    </script>
}
@section Stylesheets {
    <environment names="Development">
        <link rel="stylesheet" href="~/lib/medium-editor/dist/css/medium-editor.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/medium-editor/dist/css/themes/default.css" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="~/lib/medium-editor/dist/css/medium-editor.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/lib/medium-editor/dist/css/themes/default.min.css" asp-append-version="true" />
    </environment>
}

<form class="pure-form pure-g">
    <input asp-for="PostId" type="hidden" class="pure-input-1" />

    <div class="pure-u-1 pure-u-md-1-2">
        <div class="form-group">
            <label asp-for="Title"></label>
            <input class="pure-input-1" asp-for="Title" />
        </div>
        <div class="form-group">
            <label asp-for="UrlPath"></label>
            <input class="pure-input-1" asp-for="UrlPath" />
        </div>
    </div>

    <div class="pure-u-1 pure-u-md-1-2">
        <div class="form-group">
            <label asp-for="SelectedBlogId"></label>
            <select asp-for="SelectedBlogId" asp-items="Model.BlogOptions"></select>
        </div>
        <div class="form-group">
            <label asp-for="TagString"></label>
            <input class="pure-input-1" asp-for="TagString" />
        </div>
    </div>

    <div class="pure-u-1">
        <div class="form-group">
            <label asp-for="Blurb"></label>
            <textarea asp-for="Blurb"></textarea>
        </div>

        <div class="form-group">
            <textarea asp-for="Content" class="editable">
        </textarea>
        </div>

        @* todo: fix, this is not displaying when validating. *@
        <div asp-validation-summary="All" class="text-danger" style="display:none;"></div>

        <div style="text-align:center">
            <button formmethod="post" asp-action="SaveDraftPost" asp-controller="Blogging" class="pure-button pure-button-primary">save as draft</button>
            <button formmethod="post" asp-action="PublishPost" asp-controller="Blogging" class="pure-button">publish post</button>
            @*<button type="submit" asp-route="" formaction="SaveDraftPost" formmethod="post" class="pure-button pure-button-primary">save as draft</button>
            <button type="submit" asp-route="" formaction="PublishPost" formmethod="post" class="pure-button">publish post</button>*@
        </div>
    </div>

    @Html.AntiForgeryToken()
</form>

@section SidebarRight {
    <div class="drafts-sidebar">
        @foreach (Post post in Model.Posts)
        {
            <a asp-area="" asp-controller="Blogging" asp-action="Editor" asp-route-id="@post.UrlPath">
                <div class="drafts-sidebar-post">
                    <h3>@post.Title</h3>
                    <p>@post.Blurb</p>
                </div>
            </a>
        }
    </div>
}

chompy/Views/Blogging/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

Hello. And welcome.

chompy/Views/Blogging/Post.cshtml
@model Chompy.Models.BloggingViewModels.PostViewModel

@{
    ViewData["Title"] = Model.Post.Title;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>@Model.Post.ModifiedTimestamp</p>

@Html.Raw(Model.Post.Content)

@section SidebarRight {
    <div class="post-sidebar">
        @foreach (Post post in Model.MorePosts)
        {
            <a asp-area="" asp-controller="Blogging" asp-action="Post" asp-route-id="@post.UrlPath">
                <div class="drafts-sidebar-post">
                    <h3>@post.Title</h3>
                    <p>@post.Blurb</p>
                </div>
            </a>
        }
    </div>
}

chompy/Views/Blogging/Posts.cshtml
@model Chompy.Models.BloggingViewModels.PostsViewModel

@{
    ViewData["Title"] = "Posts";
}

<!-- todo: replace prod scripts with CDNs-->
@section Scripts {
    <environment names="Development">
        <script type="text/javascript" src="~/lib/jquery/dist/jquery.js"></script>
        <script type="text/javascript" src="~/lib/knockout/dist/knockout.debug.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script type="text/javascript" src="~/lib/jquery/dist/jquery.min.js"></script>
        <script type="text/javascript" src="~/lib/knockout/dist/knockout.js"></script>
    </environment>

    <script type="text/javascript">
        function Post(data) {
            var self = this;


        }

        function Tags(tags) {
            var self = this;
            self.tags = tags;
        }

        function ViewModel() {
            var self = this;

            self.posts = ko.observableArray();
            self.tags = ko.observableArray("todo");

            self.toggleTagFilter = function () { }
            self.tagFilterAll = function () { }
            self.tagFilterNone = function () { }
        };

        ko.applyBindings(ViewModel);
    </script>
}

<div class="pure-g">
    @foreach (Post post in Model.Posts)
    {
        <div class="pure-u-1 pure-u-lg-1-2">
            <a asp-area="" asp-controller="Blogging" asp-action="Post" asp-route-id="@post.UrlPath">
                <div class="posts-post">
                    <h3>@post.Title</h3>
                    <p>@post.Blurb</p>
                    @foreach (PostTag postTag in post.PostTags)
                    {
                        <div class="posttag">
                            @postTag.Tag.Label
                        </div>
                    }
                </div>
            </a>
        </div>
    }
</div>

@section SidebarRight {
    <div class="tag-filters-sidebar pure-g-r">
        <div class="flexbox-center">
            <h3>filter by tag</h3>

            <button class="filter-tag" id="filter-tag-selectall" data-bind="click: tagFilterAll">
                select all
            </button>
            <button class="filter-tag" id="filter-tag-selectnone" data-bind="click: tagFilterNone">
                select none
            </button>

            <br />

            @foreach (Tag tag in Model.Tags)
            {
                <button class="filter-tag" id="filter-tag-@tag.TagId" data-bind="click: toggleTagFilter">
                    @tag.Label
                </button>
            }
        </div>
    </div>
}

chompy/Views/Blogging/Submit.cshtml
@{
    ViewData["Title"] = "Submit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Submit</h2>